Feat: Added delete button for items that connects to database
the-collab-lab/tcl-13-smart-shopping-list pull request #31
Opened 2020-11-10 22:32 UTC by audracodes

## Description

This PR adds a delete button to each item in a user's shopping list. Upon clicking the delete button the user is prompted to ensure that they'd like to delete the item, if they click `ok` then the item is removed from their list and the database. 

## Related Issue

Closes #11 

## Acceptance Criteria

- [x] User is able to delete an item from the shopping list
- [x] Before deleting, prompt the user to confirm that they really want to delete the item to prevent accidental deletions
-[x] Deletion should cause the associated record(s) in the database to be deleted

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
| ✓ | :sparkles: New feature     |
| ✓| :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

**ViewList**

Added a `button` to the `li` of the rendered user list, when the button is clicked `handleDelete` runs. `handleDelete` uses `confirm` to show a prompt to the user asking if they'd like to delete their item. If the user clicks `ok` then the item is removed from the database. 

The checkbox input from the list was also moved into the `li` to make the UI more straight forward.

### Before

![Screen Shot 2020-11-10 at 3 36 25 PM](https://user-images.githubusercontent.com/49924080/98741207-3d846080-237a-11eb-9daf-3f19fb2f8922.png)

### After

![Screen Shot 2020-11-10 at 3 35 46 PM](https://user-images.githubusercontent.com/49924080/98741227-4bd27c80-237a-11eb-9005-8decf8430538.png)

![Screen Shot 2020-11-10 at 3 35 53 PM](https://user-images.githubusercontent.com/49924080/98741239-4ffe9a00-237a-11eb-9e01-5a262969d0e4.png)

## Testing Steps / QA Criteria

Make sure you are viewing a list that contains items. In the `ViewList` component, each list item should have a delete button beside the name of the item. Upon clicking delete a prompt should appear asking for confirmation of deletion. After clicking 'ok' the item should be removed from the list and from the database.

2020-11-11 00:10 UTC, rachel-fischoff commented
@snsebro @rbompiani ready for review!

2020-11-12 21:19 UTC, rbompiani requested changes
Looks good!  Just needs a catch to divert from deleting the item from the database if the user cancels via the confirm window.

2020-11-12 21:19 UTC, rbompiani commented on src/components/ViewList.js
> +    window.confirm('Would you like to delete your item?');
Clicking "cancel" in the confirm still deletes the item from the database.  We'll need something here to conditionally delete based on the confirm response.

2020-11-12 21:19 UTC, rbompiani commented on src/components/ViewList.js
> +              <li>
I like this nesting a lot more than what we had previously. Shayne and I had a few edits here as well (styling, mostly). When merging we should keep this nesting but move class styling from the other issue.

2020-11-13 03:17 UTC, rbompiani approved these changes

2020-11-14 00:41 UTC, indiragp approved these changes
Great Job!

2020-11-14 19:09 UTC, merged